version: '3.5'

services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - DB_HOST=db
    ports:
      - '${LINK_SERVICE_LOCAL_PORT}:${LINK_SERVICE_DOCKER_PORT}'
    depends_on:
      db:
        condition: service_healthy  # Wait for the healthcheck to succeed
    volumes:
      - ./src:/app/src
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      db:
        condition: service_healthy  # Wait for the healthcheck to succeed
    networks:
      - mynetwork

networks:
  mynetwork:
